# Generated by Django 5.0.6 on 2024-05-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0003_remove_quiz_category_remove_option_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre del Producto')),
                ('imagen', models.ImageField(blank=True, upload_to='productos', verbose_name='Imagen')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
            ],
        ),
    ]
