# Generated by Django 5.0.6 on 2024-05-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
